# Don't print a new line at the start of the prompt
add_newline = false

format = """
[â”Œâ”€](white)$directory$time $git_branch$git_commit$git_state$git_status
[â””â”€â”€>](white) $username $character
"""

# format = """
# [â”Œâ”€](white)$directory$time $git_branch$git_commit$git_state$git_status$package$cmake$dart$dotnet$premake$golang$java$kotlin$nodejs$perl$php$python$ruby$rust
# [â””â”€â”€>](white) $username $character
# """


[character]
success_symbol = "[ï‘ ](green)"
error_symbol = "[ï‘ ](red)"
vicmd_symbol = "[ï‘½](yellow)"

[directory]
truncation_length = 32
truncation_symbol = ""
truncate_to_repo = false 
format = '[\[](white)[$path](bold blue)[$read_only](bold red)[\]](white)'
read_only = " ï ½"

[username]
disabled = false
show_always = true
style_user = "white bold"
style_root = "yellow bold"
format = "[Î»]($style) [|](bold blue)"


[git_commit]
commit_hash_length = 4
tag_symbol = "ðŸ”– "
